/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminDashboard: typeof import('./components/admin/AdminDashboard.vue')['default']
    AdminHome: typeof import('./components/admin/admin-pages/AdminHome.vue')['default']
    AdminSettings: typeof import('./components/admin/admin-pages/AdminSettings.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Catplay: typeof import('./components/training/Catplay.vue')['default']
    Chat: typeof import('./components/training/Chat.vue')['default']
    Chatbot: typeof import('./components/shop/Chatbot.vue')['default']
    Counter: typeof import('./components/training/Counter.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    ImageGenerator: typeof import('./components/shop/ImageGenerator.vue')['default']
    ItemOverview: typeof import('./components/shop/ItemOverview.vue')['default']
    ItemSingleView: typeof import('./components/shop/ItemSingleView.vue')['default']
    LandingPage: typeof import('./components/LandingPage.vue')['default']
    Layout: typeof import('./components/training/Layout.vue')['default']
    Login: typeof import('./components/user/Login.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Notification: typeof import('./components/user/Notification.vue')['default']
    PicGenerator: typeof import('./components/shop/PicGenerator.vue')['default']
    Playground: typeof import('./components/training/Playground.vue')['default']
    ProductManagement: typeof import('./components/admin/admin-pages/ProductManagement.vue')['default']
    QhLanding: typeof import('./components/questhub/qh-landing.vue')['default']
    QhQuestcard: typeof import('./components/questhub/qh-questcard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopCart: typeof import('./components/shop/ShopCart.vue')['default']
    SignUp: typeof import('./components/user/SignUp.vue')['default']
    TableViews: typeof import('./components/training/TableViews.vue')['default']
    TaskCard: typeof import('./components/task-management/TaskCard.vue')['default']
    TaskDialog: typeof import('./components/task-management/TaskDialog.vue')['default']
    Tasks: typeof import('./components/task-management/Tasks.vue')['default']
    ToDoApp: typeof import('./components/todo/ToDoApp.vue')['default']
    ToDoForm: typeof import('./components/todo/ToDoForm.vue')['default']
    ToDoList: typeof import('./components/todo/ToDoList.vue')['default']
    UserManagement: typeof import('./components/admin/admin-pages/UserManagement.vue')['default']
    UserProfile: typeof import('./components/user/UserProfile.vue')['default']
    UserPurchaseHistory: typeof import('./components/user/UserPurchaseHistory.vue')['default']
    UserSettings: typeof import('./components/user/UserSettings.vue')['default']
    ValidateForm: typeof import('./components/training/ValidateForm.vue')['default']
    WorkSchedule: typeof import('./components/user/WorkSchedule.vue')['default']
  }
}
