/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Catplay: typeof import('./components/playground/Catplay.vue')['default']
    Counter: typeof import('./components/playground/Counter.vue')['default']
    Dialog: typeof import('@/components/task-management/TaskDialog.vue')['default']
    Forms: typeof import('./components/pages/Forms.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    LandingPage: typeof import('./components/LandingPage.vue')['default']
    Layout: typeof import('./components/pages/Layout.vue')['default']
    Login: typeof import('./components/user/Login.vue')['default']
    Logout: typeof import('./components/user/Logout.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    Page: typeof import('./components/Landing Page.vue')['default']
    Playground: typeof import('./components/playground/Playground.vue')['default']
    Portal: typeof import('./components/pages/Portal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUp: typeof import('./components/user/SignUp.vue')['default']
    TableViews: typeof import('./components/pages/TableViews.vue')['default']
    TaskCard: typeof import('./components/task-management/TaskCard.vue')['default']
    TaskDetails: typeof import('./components/TaskDetails.vue')['default']
    TaskDialog: typeof import('./components/task-management/TaskDialog.vue')['default']
    Tasks: typeof import('./components/task-management/Tasks.vue')['default']
    ToDoApp: typeof import('./components/todo/ToDoApp.vue')['default']
    ToDoForm: typeof import('./components/todo/ToDoForm.vue')['default']
    ToDoList: typeof import('./components/todo/ToDoList.vue')['default']
    UserProfile: typeof import('./components/user/UserProfile.vue')['default']
    UserSettings: typeof import('./components/user/UserSettings.vue')['default']
    Watch: typeof import('./components/pages/Watch.vue')['default']
  }
}
